baseURL = "https://Kaitaolie.github.io/"
title = "Kai's Tech Log"
theme = "hugo-coder"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
enableEmoji = true

[pagination]
pagerSize = 6

[markup]
[markup.highlight]
noClasses = false
style = "monokai"

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Kai"
description = "NEFU GIS"
keywords = "WSL, Termux, C/C++, GIS, 自动化"
info = ["GIS Undergraduate at NEFU", "Tech enthusiast"]
avatarURL = "images/avatar.jpg"
dateFormat = "2006年01月02日"
since = 2026
colorScheme = "auto"
hideColorSchemeToggle = false

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/Kaitaolie/"

[[menu.main]]
name = "文章"
weight = 1
url = "posts/"

[[menu.main]]
name = "关于我"
weight = 2
url = "about/"
