baseURL = "https://Kaitaolie.github.io/"
title = "Kai's Tech Log"
theme = "hugo-coder"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
enableEmoji = true

[pagination]
pagerSize = 6

[markup]
[markup.highlight]
noClasses = false
style = "monokai"

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Kai"
avatarURL = "images/avatar.jpg"
colorScheme = "auto"
hideColorSchemeToggle = false

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/Kaitaolie/"

[[menu.main]]
name = "Home"
weight = 1
url = "home/"

[[menu.main]]
name = "Context"
weight = 2
url = "posts/"

[[menu.main]]
name = "About Me"
weight = 3
url = "about/"
